using DotNet.Web.Api.Template.DTOs;
using DotNet.Web.Api.Template.DTOs.Decision;
using DotNet.Web.Api.Template.DTOs.Department;
using DotNet.Web.Api.Template.DTOs.Meeeting;
using DotNet.Web.Api.Template.DTOs.User;
using DotNet.Web.Api.Template.Models;
using DotNet.Web.Api.Template.Models.Auth;
using DotNet.Web.Api.Template.Models.Decisions;
using DotNet.Web.Api.Template.Models.FileUploads;
using AutoMapper;
using Task = DotNet.Web.Api.Template.Models.Decisions.Task;

namespace DotNet.Web.Api.Template.Helpers
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // User Mapping
            CreateMap<ApplicationUser, UserDTO>();


            // Meeting Mappings
            CreateMap<AddMeetingDto, Meeting>();
            CreateMap<Meeting, MeetingDto>();


            // Decision Mappings

            CreateMap<AddDecisionDto, Decision>()
                // Ignore BaseEntity properties for creation, as they are usually set by the service/database
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedUserId, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedUserId, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedUserId, opt => opt.Ignore())

                // Map DecisionType and Status to their default values or specific logic
                // Assuming default values from the Decision model apply
                .ForMember(dest => dest.DecisionType, opt => opt.MapFrom(src => DecisionType.Ongoing)) // Or based on DTO if added
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => DecisionStatus.Pending))   // Or based on DTO if added

                // Custom mapping for Tasks
                .ForMember(dest => dest.Tasks, opt => opt.MapFrom(src => src.Tasks))

                // Custom mapping for SelectedDepartmentIds to DecisionDepartments
                // This will create new DecisionDepartment entities
                .ForMember(dest => dest.DecisionDepartments, opt => opt.MapFrom((src, dest, context) =>
                    src.SelectedDepartmentIds.Select(departmentId => new DecisionDepartment
                    {
                        DepartmentId = departmentId,
                        // DecisionId will be set after the Decision is created and saved, or handled in the service layer
                        // Decision = context.Mapper.Map<Department>(departmentId) // If you need to map the Department object directly
                    }).ToList()
                ));

            CreateMap<Decision, DecisionDto>()
                .ForMember(dest => dest.Departments, opt => opt.MapFrom(src => src.DecisionDepartments.Select(dd => dd.Department).Distinct()))
                .ForMember(dest => dest.Tasks, opt => opt.MapFrom(src => src.Tasks))
                .ForMember(dest => dest.SupportDocuments, opt => opt.MapFrom(src => src.SupportDocuments));

            CreateMap<Decision, UpdateDecisionDto>().ReverseMap();


            // Task Mappings

            CreateMap<TaskCreateDto, Task>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Id is typically generated by DB, or set in service
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set in service or database
                .ForMember(dest => dest.CreatedUserId, opt => opt.Ignore()) // Set in service
                .ForMember(dest => dest.isCompleted, opt => opt.MapFrom(src => false)) // Default value or map from DTO if present
                .ForMember(dest => dest.DecisionId, opt => opt.Ignore()) // DecisionId will be set when adding tasks to a decision
                                                                         // Highlighted Change: Custom mapping for AssignedDepartmentIds to TaskDepartments
                .ForMember(dest => dest.TaskDepartments, opt => opt.MapFrom((src, dest, context) =>
                    src.AssignedDepartmentIds.Select(departmentId => new TaskDepartment
                    {
                        DepartmentId = departmentId,
                        // TaskId will be set after the Task is created and saved, or handled in the service layer
                    }).ToList()
                ));

            CreateMap<Task, TaskReadDto>()
                .ForMember(dest => dest.IsCompleted, opt => opt.MapFrom(src => src.isCompleted))
                .ForMember(dest => dest.Departments, opt => opt.MapFrom(src => src.TaskDepartments.Select(td => td.Department).Distinct()));

            CreateMap<Task, TaskDTO>().ReverseMap();

            CreateMap<SupportDocumentCreateDto, SupportDocument>();

            CreateMap<DecisionUpdateDto, Decision>();
            //.ForMember(dest => dest.DecisionDepartments, opt => opt.MapFrom(src =>
            //    src.Tasks
            //        .SelectMany(t => t.AssignedDepartmentIds)
            //        .Distinct()
            //        .Select(departmentId => new DecisionDepartment { DepartmentId = departmentId, DecisionId = src.Id })));



            // Meeting Mappings (existing)
            CreateMap<MeetingCreateDto, Meeting>()
                .ForMember(dest => dest.MeetingDepartments, opt => opt.Ignore()) // Handled manually in service
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            CreateMap<MeetingUpdateDto, Meeting>()
                 .ForMember(dest => dest.MeetingDepartments, opt => opt.Ignore()) // Handled manually in service
                 .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                 .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            CreateMap<Meeting, MeetingReadDto>()
                .ForMember(dest => dest.Departments, opt => opt.MapFrom(src => src.MeetingDepartments.Select(md => md.Department)));

            CreateMap<Department, DepartmentReadDto>(); // For mapping departments within MeetingReadDto and now DecisionReadDto


            // Department Mapping
            CreateMap<Department, DepartmentDto>();
            CreateMap<AddDepartmentDto, Department>();
            CreateMap<UpdateDepartmentDto, Department>();
            CreateMap<Department, DepartmentWithAllDataDto>();
            CreateMap<ApplicationUser, DepartmentUserDto>();


            // SupportDocument Mapping
            CreateMap<SupportDocument, SupportDocumentReadDto>()
                .ForMember(dest => dest.UploadDate, opt => opt.MapFrom(src => src.CreatedAt)); // Assuming UploadDate maps to CreatedAt from BaseEntity
            CreateMap<SupportDocument, SupportDocumentDto>();
        }
    }
}